### ISSUE TITLE
How can we best support and interest driven / multiple path approach to making games

### ISSUE THREAD

**Issue by mickfuzz** [glitch-game-club/glitch-game-club#12]
Any suggestions from educators and volunteers about how best to present our resources in a way that supports different pathways through the material, tools and activities that are part of the process of making web games? 

There is a start of [page on a wiki here that would be turn into more colorful resources](https://github.com/mickfuzz/mozilla-webgame-clubs/wiki). But how to do it without giving the impression that there is a set path to follow in a particular order?

**Comment by davegoopot** [comment]
I've struggled with this one at the Mcr CoderDojo. Our format is 3hrs once per month. The problem is getting something self-contained in that time that isn't too much painting-by-numbers. Most people we have turning up have no background in whatever technical topic we've decided to cover.

The sessions that have worked best for us are ones where the first half is taken copying something reasonably by-rote following written instructions to get an example of something working followed by a second half having space to tinker with that idea to come up with something new. 

It may be a different dynamic with the web games club assuming you have the same participants back each week and can build up skills with more practice.

Not an answer to the question I know. Rather my observation  is that it is difficult!

**Comment by mickfuzz** [comment]
That is a really useful observation Dave. I think that here's a lot to be said for being realistic about the timescale for activities for the monthly dojo. And it is definitely worth thinking about a stream of activities that are self contained and work worth within that kind of set up. As that is the norm.

I feel very lucky having some groups that are every week or two weeks. It makes it more flexible to do things you know you don't have to finish in that session. 

I guess if we are talking about making game assets, like pixel art / sound. Then maybe there is something to be said for a theme that lasts 6 months or so. And as you accumulate assets around that theme you can highlight them to the new folk that come along. And then towards the end you can start to recombine them in your web game.

**Comment by mickfuzz** [comment]
I've been thinking a bit more about this and gettting feedback from the Tuesday coding club participants too.  I'm thinking that a really restricted set of technologies but lots of flexibility of how and when you work with them would respond to the concerns and the reactions of those involved. 

- Phaser
- Thimble (codepen as a backup)
- Piskel for pixel art
- Sonic Pi for music
- Chiptone for combined sampler & FX http://sfbgames.com/chiptone- 

Are the ones that seem tried and tested. This means losing audacity but I think that is ok with the Chiptone sampler in there.

**Comment by mickfuzz** [comment]
This could perhaps do with a chapter in Part Two of this book. 
http://write.flossmanuals.net/learn-javascript-with-phaser
